# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TareaAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TareaAPI

  target 'TareaAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TareaAPIUITests' do
    # Pods for testing
  end

end
